### ISSUE TITLE
深度校正模块训练数据集

### ISSUE THREAD

**Issue by yxy749980346** [Chen-Suyi/PointRegGPT#1]
您好，可以提供一下训练深度校正模块所使用的数据集吗，或者能否提供一下数据预处理的源代码呢

**Comment by Chen-Suyi** [comment]
感谢你对本工作的关注。

由于本人目前正在休假，抱歉无法及时更新完整版README。
部分README内容已更新，其中包含了你所需要的数据集链接。

有关训练数据读取和预处理部分的代码可以参考[这里](example_dataloader)。
关于TSDF融合点云的处理过程可以直接参考[3dmatch-toolbox](https://github.com/andyzeng/3dmatch-toolbox)及其[Python实现](https://github.com/andyzeng/tsdf-fusion-python)。我们在用Python实现时使用了[Open3D的TSDF实现](https://www.open3d.org/docs/latest/python_api/open3d.pipelines.integration.ScalableTSDFVolume.html#open3d.pipelines.integration.ScalableTSDFVolume)。

后续我们还将提供全套的权重以方便复现，敬请期待。

**Comment by yxy749980346** [comment]
感谢您的回复！
